import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/Header/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "DhwaniAstro-Admin Panel",
  description: "Generated by create next app",
  icon:{
    icon: "/src/app/favicon.ico"
  }
};

export default function RootLayout({ children }) {
  return (
 
        <html lang="en">
          <body  className={`${geistSans.variable} ${geistMono.variable} antialiased`}>       
          {/* <Header/> */}    
        
            <div >{children}</div>    
       
            {/* <footer>My Footer</footer> */}
          </body>
        </html>
  );
}
